# FERNan Discord Komut Skripti
command discord:
    trigger:
        send "" to player
        send "&x&3&7&B&F&F&9ғᴀsᴛᴇʀsᴍᴘ ɴɪɴ ᴅɪsᴄᴏʀᴅ sᴜɴᴜᴄᴜsᴜɴᴀ ᴋᴀᴛıʟ!" to player
        send "&x&3&7&B&F&F&9● <link:https://discord.gg/.....)" to player
        send "" to player
        send action bar "&7The link has been sent in chat!" to player
        play sound "minecraft:entity.experience_orb.pickup" with volume 1 and pitch 1 to player